weights:
  person_conf: 0.10
  hand_item_prob: 0.10
  cig_prob: 0.15
  vape_prob: 0.15
  h2m_prob: 0.20
  smoke_prob: 0.25
  emission_prob: 0.10
  action_prob: 0.20
  firecracker_prob: -0.15
bias: 0.0
clamp_min: 0.0
clamp_max: 1.0

thresholds:
  unlikely: 0.25
  low: 0.50
  moderate: 0.70
  high: 0.85
